
ALTER TABLE public.chart_analysis_logs
  ADD COLUMN IF NOT EXISTS mn_tp1 TEXT,
  ADD COLUMN IF NOT EXISTS mn_tp2 TEXT,
  ADD COLUMN IF NOT EXISTS mn_checkpoint TEXT,
  ADD COLUMN IF NOT EXISTS w_tp1 TEXT,
  ADD COLUMN IF NOT EXISTS w_tp2 TEXT,
  ADD COLUMN IF NOT EXISTS w_checkpoint TEXT,
  ADD COLUMN IF NOT EXISTS d_tp1 TEXT,
  ADD COLUMN IF NOT EXISTS d_tp2 TEXT,
  ADD COLUMN IF NOT EXISTS d_checkpoint TEXT,
  ADD COLUMN IF NOT EXISTS h4_tp1 TEXT,
  ADD COLUMN IF NOT EXISTS h4_tp2 TEXT,
  ADD COLUMN IF NOT EXISTS h4_checkpoint TEXT,
  ADD COLUMN IF NOT EXISTS h1_tp1 TEXT,
  ADD COLUMN IF NOT EXISTS h1_tp2 TEXT,
  ADD COLUMN IF NOT EXISTS h1_checkpoint TEXT;
